name: testssl.sh CI

on:
  push:
    paths-ignore:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'
    pull_request:
      - 'utils/**'
      - 'doc/**'
      - 'bin/**'
      - '**.md'
      - '**.pem'
      - '**.pdf'
      - '**.html'
      - 'LICENSE'
      - 'Dockerfile'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04']
        perl: ['5.26']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install deps
        run: sudo apt install dnsutils jsonlint
      - run: cpanm --notest Test::More
      - run: cpanm --notest Data::Dumper
      - run: cpanm --notest JSON
      - run: cpanm --notest Text::Diff
      - run: prove -v
